/**
 * @file pdf_writer.hpp
 * @brief Raw PDF 1.4 file writer - zero external dependencies
 * @version 5.3.1
 * @copyright (c) 2026 Bennie Shearer (Retired). MIT License.
 *
 * Generates valid PDF 1.4 output directly from C++:
 *   - Text (multiple fonts: Helvetica, Helvetica-Bold, Courier)
 *   - Tables with borders and alignment
 *   - Headers, subtitles, paragraphs
 *   - Key-value sections
 *   - Page numbers and footers
 *   - Page breaks
 *   - A4 and US Letter page sizes
 *
 * Integrates with ReportDocument from pdf_report.hpp to convert
 * existing report structures directly to PDF binary output.
 *
 * PDF 1.4 Reference: ISO 32000-1:2008 (subset)
 */
#pragma once
#ifndef GENIE_REPORTING_PDF_WRITER_HPP
#define GENIE_REPORTING_PDF_WRITER_HPP

#include "pdf_report.hpp"
#include <string>
#include <vector>
#include <sstream>
#include <iomanip>
#include <cmath>
#include <fstream>
#include <cstring>

namespace genie::reporting {

/**
 * @brief Page size presets (points: 1 pt = 1/72 inch)
 */
struct PageSize {
    double width;
    double height;

    static PageSize letter() { return {612, 792}; }
    static PageSize a4() { return {595.28, 841.89}; }
};

/**
 * @brief Minimal PDF 1.4 writer
 *
 * Objects are numbered starting at 1. The writer accumulates objects,
 * then writes the cross-reference table and trailer at the end.
 */
class PdfWriter {
public:
    struct Style {
        PageSize page{612, 792};   // US Letter
        double margin_left{50};
        double margin_right{50};
        double margin_top{50};
        double margin_bottom{60};
        double line_spacing{1.4};
        std::string title_font{"Helvetica-Bold"};
        double title_size{18};
        std::string subtitle_font{"Helvetica-Bold"};
        double subtitle_size{14};
        std::string body_font{"Helvetica"};
        double body_size{10};
        std::string header_font{"Helvetica-Bold"};
        double header_size{8};
        double table_font_size{9};
        std::string footer_text{"Generated by Metis Genie Platform Investment Platform"};
    };

    PdfWriter() : style_() {}
    explicit PdfWriter(const Style& style) : style_(style) {}

    /**
     * @brief Convert a ReportDocument to PDF bytes
     */
    std::string render(const ReportDocument& doc) {
        reset();

        // Render all elements across pages
        begin_page();

        for (const auto& el : doc.elements) {
            switch (el.type) {
                case ElementType::Title:
                    ensure_space(style_.title_size * style_.line_spacing + 10);
                    write_text(el.text, style_.title_font, style_.title_size, 0.1, 0.2, 0.4);
                    y_ -= 6; // extra spacing after title
                    // Underline
                    draw_line(style_.margin_left, y_,
                              style_.page.width - style_.margin_right, y_, 1.0, 0.2, 0.4, 0.7);
                    y_ -= 8;
                    break;

                case ElementType::Subtitle:
                    ensure_space(style_.subtitle_size * style_.line_spacing + 8);
                    y_ -= 6;
                    write_text(el.text, style_.subtitle_font, style_.subtitle_size, 0.15, 0.2, 0.3);
                    y_ -= 4;
                    break;

                case ElementType::Paragraph:
                    write_paragraph(el.text, style_.body_font, style_.body_size);
                    y_ -= 4;
                    break;

                case ElementType::KeyValue:
                    ensure_space((el.kv_pairs.size() + 1) * style_.body_size * style_.line_spacing + 20);
                    if (!el.text.empty()) {
                        write_text(el.text, style_.subtitle_font, 11, 0.2, 0.25, 0.35);
                        y_ -= 4;
                    }
                    for (const auto& [k, v] : el.kv_pairs) {
                        ensure_space(style_.body_size * style_.line_spacing + 2);
                        write_text_at(style_.margin_left, y_, k, "Helvetica-Bold",
                                      style_.body_size, 0.3, 0.35, 0.4);
                        write_text_at(style_.margin_left + 160, y_, v, style_.body_font,
                                      style_.body_size, 0.1, 0.1, 0.1);
                        y_ -= style_.body_size * style_.line_spacing;
                    }
                    y_ -= 6;
                    break;

                case ElementType::Table:
                    render_table(el);
                    break;

                case ElementType::Divider:
                    ensure_space(16);
                    y_ -= 8;
                    draw_line(style_.margin_left, y_,
                              style_.page.width - style_.margin_right, y_,
                              0.5, 0.8, 0.85, 0.9);
                    y_ -= 8;
                    break;

                case ElementType::PageBreak:
                    end_page();
                    begin_page();
                    break;

                case ElementType::Chart:
                    if (el.chart_data.empty()) {
                        ensure_space(20);
                        write_text("[No chart data]", "Courier", style_.body_size, 0.5, 0.5, 0.5);
                        break;
                    }
                    render_chart(el);
                    break;
            }
        }

        // Footer on last page
        end_page();

        return build_pdf();
    }

    /**
     * @brief Write PDF to file
     */
    bool write_to_file(const ReportDocument& doc, const std::string& path) {
        std::string pdf = render(doc);
        std::ofstream file(path, std::ios::binary);
        if (!file) return false;
        file.write(pdf.data(), pdf.size());
        return file.good();
    }

private:
    Style style_;

    // State
    double y_{0};
    int page_count_{0};
    int current_page_obj_{0};

    // PDF objects (1-indexed)
    std::vector<std::string> objects_;
    std::vector<int> page_objects_;

    // Current page content stream
    std::ostringstream page_stream_;

    void reset() {
        objects_.clear();
        page_objects_.clear();
        page_count_ = 0;
        y_ = 0;
    }

    int add_object(const std::string& content) {
        objects_.push_back(content);
        return static_cast<int>(objects_.size()); // 1-indexed
    }

    double usable_width() const {
        return style_.page.width - style_.margin_left - style_.margin_right;
    }

    // --- Page Management ---

    void begin_page() {
        page_count_++;
        y_ = style_.page.height - style_.margin_top;
        page_stream_.str("");
        page_stream_.clear();
    }

    void end_page() {
        // Add footer
        write_footer();

        // Create content stream object
        std::string stream_content = page_stream_.str();
        std::ostringstream obj;
        obj << "<< /Length " << stream_content.size() << " >>\n"
            << "stream\n" << stream_content << "endstream";
        int stream_obj = add_object(obj.str());

        // Create page object (placeholder - will be filled in build_pdf)
        std::ostringstream page;
        page << "<< /Type /Page\n"
             << "   /MediaBox [0 0 " << style_.page.width << " " << style_.page.height << "]\n"
             << "   /Contents " << stream_obj << " 0 R\n"
             << "   /Resources << /Font << /F1 {F1_REF} /F2 {F2_REF} /F3 {F3_REF} >> >>\n"
             << "   /Parent {PAGES_REF}\n"
             << ">>";
        int page_obj = add_object(page.str());
        page_objects_.push_back(page_obj);
    }

    void ensure_space(double needed) {
        if (y_ - needed < style_.margin_bottom) {
            end_page();
            begin_page();
        }
    }

    // --- Text Rendering ---

    void write_text(const std::string& text, const std::string& font,
                    double size, double r, double g, double b) {
        write_text_at(style_.margin_left, y_, text, font, size, r, g, b);
        y_ -= size * style_.line_spacing;
    }

    void write_text_at(double x, double y, const std::string& text,
                        const std::string& font, double size,
                        double r, double g, double b) {
        std::string font_ref = font_to_ref(font);
        page_stream_ << "BT\n"
                      << std::fixed << std::setprecision(2)
                      << r << " " << g << " " << b << " rg\n"
                      << font_ref << " " << size << " Tf\n"
                      << x << " " << y << " Td\n"
                      << "(" << escape_pdf(text) << ") Tj\n"
                      << "ET\n";
    }

    void write_paragraph(const std::string& text, const std::string& font, double size) {
        // Simple word wrapping
        double max_width = usable_width();
        double char_width = size * 0.5; // approximate for Helvetica
        int chars_per_line = static_cast<int>(max_width / char_width);
        if (chars_per_line < 20) chars_per_line = 20;

        std::istringstream words(text);
        std::string word;
        std::string line;
        
        while (words >> word) {
            if (line.empty()) {
                line = word;
            } else if (static_cast<int>(line.size() + 1 + word.size()) <= chars_per_line) {
                line += " " + word;
            } else {
                ensure_space(size * style_.line_spacing);
                write_text(line, font, size, 0.1, 0.1, 0.1);
                line = word;
            }
        }
        if (!line.empty()) {
            ensure_space(size * style_.line_spacing);
            write_text(line, font, size, 0.1, 0.1, 0.1);
        }
    }

    // --- Table Rendering ---

    void render_table(const ReportElement& el) {
        if (el.columns.empty() || el.rows.empty()) return;

        double font_size = style_.table_font_size;
        double row_height = font_size * 1.8;
        double table_width = usable_width();
        int num_cols = static_cast<int>(el.columns.size());

        // Calculate column widths
        std::vector<double> col_widths(num_cols);
        double total_pct = 0;
        for (int i = 0; i < num_cols; ++i) {
            total_pct += el.columns[i].width_pct > 0 ? el.columns[i].width_pct : 100.0 / num_cols;
        }
        for (int i = 0; i < num_cols; ++i) {
            double pct = el.columns[i].width_pct > 0 ? el.columns[i].width_pct : 100.0 / num_cols;
            col_widths[i] = table_width * (pct / total_pct);
        }

        // Table title
        if (!el.text.empty()) {
            ensure_space(12 * style_.line_spacing + row_height * 2);
            write_text(el.text, "Helvetica-Bold", 11, 0.2, 0.25, 0.35);
            y_ -= 4;
        }

        // Header row
        ensure_space(row_height * 2);
        double x = style_.margin_left;

        // Header background
        draw_rect(x, y_ - row_height + 4, table_width, row_height, 0.93, 0.95, 0.97, true);

        for (int c = 0; c < num_cols; ++c) {
            write_text_at(x + 4, y_ - font_size * 0.3, el.columns[c].header,
                          "Helvetica-Bold", font_size - 1, 0.2, 0.25, 0.3);
            // Vertical line
            draw_line(x, y_ + 4, x, y_ - row_height + 4, 0.3, 0.88, 0.9, 0.93);
            x += col_widths[c];
        }
        // Right border
        draw_line(x, y_ + 4, x, y_ - row_height + 4, 0.3, 0.88, 0.9, 0.93);
        // Bottom border
        draw_line(style_.margin_left, y_ - row_height + 4,
                  style_.margin_left + table_width, y_ - row_height + 4,
                  0.3, 0.88, 0.9, 0.93);

        y_ -= row_height;

        // Data rows
        for (size_t r = 0; r < el.rows.size(); ++r) {
            ensure_space(row_height);

            // Alternating row background
            if (r % 2 == 0) {
                draw_rect(style_.margin_left, y_ - row_height + 4,
                          table_width, row_height, 0.97, 0.98, 0.99, true);
            }

            x = style_.margin_left;
            for (int c = 0; c < num_cols && c < static_cast<int>(el.rows[r].size()); ++c) {
                double text_x = x + 4;
                if (el.columns[c].align == Align::Right) {
                    // Approximate right alignment
                    double text_w = el.rows[r][c].size() * font_size * 0.45;
                    text_x = x + col_widths[c] - text_w - 4;
                    if (text_x < x + 4) text_x = x + 4;
                }

                write_text_at(text_x, y_ - font_size * 0.3, el.rows[r][c],
                              style_.body_font, font_size - 1, 0.15, 0.15, 0.15);
                x += col_widths[c];
            }

            // Row bottom border
            draw_line(style_.margin_left, y_ - row_height + 4,
                      style_.margin_left + table_width, y_ - row_height + 4,
                      0.2, 0.9, 0.92, 0.94);

            y_ -= row_height;
        }

        y_ -= 8;
    }

    // --- Drawing Primitives ---

    void draw_line(double x1, double y1, double x2, double y2,
                   double width, double r, double g, double b) {
        page_stream_ << std::fixed << std::setprecision(2)
                      << r << " " << g << " " << b << " RG\n"
                      << width << " w\n"
                      << x1 << " " << y1 << " m\n"
                      << x2 << " " << y2 << " l\n"
                      << "S\n";
    }

    void draw_rect(double x, double y, double w, double h,
                   double r, double g, double b, bool fill) {
        page_stream_ << std::fixed << std::setprecision(2)
                      << r << " " << g << " " << b << (fill ? " rg\n" : " RG\n")
                      << x << " " << y << " " << w << " " << h << " re\n"
                      << (fill ? "f\n" : "S\n");
    }
    
    /**
     * @brief Render chart as horizontal bar chart + data table
     *
     * Uses PDF drawing primitives (filled rectangles and text) to render
     * actual visual bar charts directly in PDF output. Also includes a 
     * data table below for precise values. For pie chart types, shows
     * a percentage breakdown with color-coded swatches.
     */
    void render_chart(const ReportElement& el) {
        const auto& data = el.chart_data;
        if (data.empty()) return;
        
        // Find max value for scaling
        double max_val = 0;
        double total = 0;
        for (const auto& [label, value] : data) {
            if (std::abs(value) > max_val) max_val = std::abs(value);
            total += value;
        }
        if (max_val == 0) max_val = 1;
        
        // Color palette for bars (professional blue/teal tones)
        struct BarColor { double r, g, b; };
        const BarColor colors[] = {
            {0.22, 0.46, 0.71},   // Steel blue
            {0.30, 0.69, 0.64},   // Teal
            {0.50, 0.38, 0.67},   // Purple
            {0.87, 0.52, 0.24},   // Orange
            {0.33, 0.66, 0.41},   // Green
            {0.77, 0.31, 0.32},   // Red
            {0.51, 0.51, 0.51},   // Gray
            {0.74, 0.62, 0.22},   // Gold
        };
        int num_colors = sizeof(colors) / sizeof(colors[0]);
        
        double bar_height = 14;
        double bar_gap = 4;
        double label_width = 120;
        double value_width = 60;
        double chart_left = style_.margin_left + label_width;
        double chart_width = style_.page.width - style_.margin_right - chart_left - value_width;
        double row_height = bar_height + bar_gap;
        
        // Space needed: title + all bars + padding
        double total_height = 24 + data.size() * row_height + 10;
        ensure_space(total_height);
        
        // Chart title
        write_text(el.text, style_.subtitle_font, 11, 0.15, 0.2, 0.3);
        y_ -= 6;
        
        // Draw bars
        for (size_t i = 0; i < data.size(); i++) {
            const auto& [label, value] = data[i];
            const auto& color = colors[i % num_colors];
            
            ensure_space(row_height + 4);
            
            // Label (left-aligned)
            std::string display_label = label;
            if (display_label.size() > 18) {
                display_label = display_label.substr(0, 16) + "..";
            }
            write_text_at(style_.margin_left, y_ - 3, display_label,
                          style_.body_font, 8, 0.2, 0.2, 0.2);
            
            // Bar (scaled to max value)
            double bar_w = (std::abs(value) / max_val) * chart_width;
            if (bar_w < 2) bar_w = 2;  // Minimum visible bar
            
            if (value >= 0) {
                draw_rect(chart_left, y_ - bar_height + 2, bar_w, bar_height,
                          color.r, color.g, color.b, true);
            } else {
                // Negative values: draw in red tone from right
                draw_rect(chart_left + chart_width - bar_w, y_ - bar_height + 2,
                          bar_w, bar_height, 0.85, 0.25, 0.25, true);
            }
            
            // Value label (right of bar)
            std::ostringstream val_str;
            val_str << std::fixed << std::setprecision(value >= 100 || value <= -100 ? 0 : 2)
                    << value;
            if (el.chart_type == "pie" && total > 0) {
                val_str << " (" << std::setprecision(1) << (value / total * 100) << "%)";
            }
            write_text_at(chart_left + chart_width + 4, y_ - 3, val_str.str(),
                          "Courier", 8, 0.3, 0.3, 0.3);
            
            y_ -= row_height;
        }
        
        // Axis line at chart left edge
        draw_line(chart_left, y_ + data.size() * row_height - 2,
                  chart_left, y_ + 2, 0.5, 0.6, 0.6, 0.6);
        
        y_ -= 8;
    }

    void write_footer() {
        double footer_y = style_.margin_bottom - 20;

        // Divider line
        draw_line(style_.margin_left, footer_y + 12,
                  style_.page.width - style_.margin_right, footer_y + 12,
                  0.3, 0.88, 0.9, 0.93);

        // Footer text
        write_text_at(style_.margin_left, footer_y, style_.footer_text,
                      style_.body_font, 8, 0.6, 0.65, 0.7);

        // Page number
        std::string page_str = "Page " + std::to_string(page_count_);
        double page_x = style_.page.width - style_.margin_right -
                         page_str.size() * 4.0;
        write_text_at(page_x, footer_y, page_str,
                      style_.body_font, 8, 0.6, 0.65, 0.7);
    }

    // --- PDF Assembly ---

    std::string build_pdf() {
        // Create font objects (using standard PDF fonts - no embedding needed)
        int f1 = add_object("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
        int f2 = add_object("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
        int f3 = add_object("<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>");

        // Create pages object
        std::ostringstream pages_kids;
        pages_kids << "<< /Type /Pages\n   /Kids [";
        for (size_t i = 0; i < page_objects_.size(); ++i) {
            if (i > 0) pages_kids << " ";
            pages_kids << page_objects_[i] << " 0 R";
        }
        pages_kids << "]\n   /Count " << page_objects_.size() << "\n>>";
        int pages_obj = add_object(pages_kids.str());

        // Fix up page object references
        for (int page_idx : page_objects_) {
            std::string& obj = objects_[page_idx - 1];
            replace_all(obj, "{F1_REF}", std::to_string(f1) + " 0 R");
            replace_all(obj, "{F2_REF}", std::to_string(f2) + " 0 R");
            replace_all(obj, "{F3_REF}", std::to_string(f3) + " 0 R");
            replace_all(obj, "{PAGES_REF}", std::to_string(pages_obj) + " 0 R");
        }

        // Catalog
        int catalog = add_object("<< /Type /Catalog\n   /Pages " +
                                  std::to_string(pages_obj) + " 0 R\n>>");

        // Now write the actual PDF
        std::ostringstream pdf;
        pdf << "%PDF-1.4\n";
        // Binary comment to mark as binary (per spec recommendation)
        pdf << "%" << char(0xE2) << char(0xE3) << char(0xCF) << char(0xD3) << "\n";

        // Write objects and record byte offsets
        std::vector<size_t> offsets(objects_.size());
        for (size_t i = 0; i < objects_.size(); ++i) {
            offsets[i] = pdf.str().size();
            pdf << (i + 1) << " 0 obj\n" << objects_[i] << "\nendobj\n";
        }

        // Cross-reference table
        size_t xref_offset = pdf.str().size();
        pdf << "xref\n";
        pdf << "0 " << (objects_.size() + 1) << "\n";
        pdf << "0000000000 65535 f \n";
        for (size_t i = 0; i < objects_.size(); ++i) {
            pdf << std::setw(10) << std::setfill('0') << offsets[i]
                << " 00000 n \n";
        }

        // Trailer
        pdf << "trailer\n";
        pdf << "<< /Size " << (objects_.size() + 1)
            << " /Root " << catalog << " 0 R >>\n";
        pdf << "startxref\n" << xref_offset << "\n%%EOF\n";

        return pdf.str();
    }

    // --- Helpers ---

    static std::string font_to_ref(const std::string& font) {
        if (font == "Helvetica-Bold") return "/F2";
        if (font == "Courier") return "/F3";
        return "/F1"; // Helvetica
    }

    static std::string escape_pdf(const std::string& s) {
        std::string result;
        result.reserve(s.size());
        for (char c : s) {
            if (c == '(' || c == ')' || c == '\\') {
                result += '\\';
            }
            // Replace non-ASCII with space for PDF safety
            if (static_cast<unsigned char>(c) > 127) {
                result += ' ';
            } else {
                result += c;
            }
        }
        return result;
    }

    static void replace_all(std::string& str, const std::string& from, const std::string& to) {
        size_t pos = 0;
        while ((pos = str.find(from, pos)) != std::string::npos) {
            str.replace(pos, from.length(), to);
            pos += to.length();
        }
    }
};

} // namespace genie::reporting

#endif // GENIE_REPORTING_PDF_WRITER_HPP
