/**
 * @file reporting_extended.hpp
 * @brief Extended reporting with account statements, tax reports, and risk reports
 * @version 5.3.1
 * @copyright (c) 2026 Bennie Shearer (Retired). MIT License.
 * 
 * Extended reporting functionality including:
 * - Account statement generation (HTML)
 * - Performance reports with actual returns
 * - Trade confirmation documents
 * - Tax report export (Form 8949)
 * - Risk reports with VaR calculations
 */
#pragma once
#ifndef GENIE_REPORTING_EXTENDED_HPP
#define GENIE_REPORTING_EXTENDED_HPP

#include "reporting.hpp"
#include "../trading/broker_abstraction.hpp"
#include "../tax/tax_tracking.hpp"
#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <iomanip>
#include <chrono>
#include <ctime>
#include <fstream>
#include <cmath>

namespace genie::reporting {

// ============================================================================
// Utility Functions
// ============================================================================

inline std::string current_datetime_str() {
    auto now = std::chrono::system_clock::now();
    auto time = std::chrono::system_clock::to_time_t(now);
    std::ostringstream oss;
    oss << std::put_time(std::localtime(&time), "%Y-%m-%d %H:%M:%S");
    return oss.str();
}

inline std::string current_date_str() {
    auto now = std::chrono::system_clock::now();
    auto time = std::chrono::system_clock::to_time_t(now);
    std::ostringstream oss;
    oss << std::put_time(std::localtime(&time), "%Y-%m-%d");
    return oss.str();
}

inline std::string fmt_currency(double amount) {
    std::ostringstream oss;
    oss << "$" << std::fixed << std::setprecision(2) << amount;
    return oss.str();
}

inline std::string fmt_percent(double pct) {
    std::ostringstream oss;
    oss << std::fixed << std::setprecision(2) << pct << "%";
    return oss.str();
}

inline std::string fmt_number(double num, int precision = 2) {
    std::ostringstream oss;
    oss << std::fixed << std::setprecision(precision) << num;
    return oss.str();
}

// ============================================================================
// Extended Report Configuration
// ============================================================================

/**
 * @brief Extended report configuration
 */
struct ExtendedReportConfig {
    std::string title;
    std::string account_name;
    std::string account_id;
    std::string period_start;
    std::string period_end;
    std::string generated_at;
    std::string logo_url;
    std::string company_name{"Metis Genie Platform Investment Management"};
    std::string footer_text{"Generated by Metis Genie Platform Investment Management Platform"};
    
    ExtendedReportConfig() {
        generated_at = current_datetime_str();
        period_end = current_date_str();
    }
};

// ============================================================================
// Enhanced HTML Report Builder
// ============================================================================

/**
 * @brief Enhanced HTML document builder
 */
class EnhancedHTMLBuilder {
public:
    void start_document(const std::string& title) {
        oss_ << R"(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>)" << title << R"(</title>
<style>
:root {
  --primary-color: #2c5282;
  --primary-light: #4299e1;
  --success-color: #38a169;
  --danger-color: #e53e3e;
  --warning-color: #d69e2e;
  --bg-color: #ffffff;
  --text-color: #2d3748;
  --border-color: #e2e8f0;
  --muted-color: #718096;
}
* { box-sizing: border-box; }
body { 
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
  margin: 0; padding: 40px; color: var(--text-color); line-height: 1.6;
  background: var(--bg-color);
}
.container { max-width: 1200px; margin: 0 auto; }
.header { 
  border-bottom: 3px solid var(--primary-color); 
  padding-bottom: 20px; margin-bottom: 30px;
}
.header h1 { color: var(--primary-color); margin: 0 0 10px 0; font-size: 2rem; }
.header .meta { color: var(--muted-color); font-size: 0.95rem; }
.section { margin: 30px 0; }
.section h2 { 
  color: var(--primary-color); 
  border-bottom: 2px solid var(--border-color); 
  padding-bottom: 10px; margin-bottom: 20px;
  font-size: 1.5rem;
}
.section h3 { color: var(--text-color); margin: 20px 0 15px 0; font-size: 1.2rem; }
table { border-collapse: collapse; width: 100%; margin: 15px 0; }
thead th { 
  background: var(--primary-color); color: white; 
  padding: 12px 10px; text-align: left; font-weight: 600;
}
tbody td { padding: 10px; border-bottom: 1px solid var(--border-color); }
tbody tr:hover { background: #f7fafc; }
.number { text-align: right; font-family: 'SF Mono', 'Monaco', 'Consolas', monospace; }
.positive { color: var(--success-color); font-weight: 500; }
.negative { color: var(--danger-color); font-weight: 500; }
.warning { color: var(--warning-color); font-weight: 500; }
.summary-box { 
  background: linear-gradient(135deg, #f7fafc 0%, #edf2f7 100%);
  border-left: 4px solid var(--primary-color); 
  padding: 20px; margin: 20px 0; border-radius: 0 8px 8px 0;
}
.metric-grid { 
  display: grid; 
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); 
  gap: 20px; margin: 20px 0;
}
.metric-card { 
  background: white; border: 1px solid var(--border-color); 
  border-radius: 12px; padding: 20px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}
.metric-label { color: var(--muted-color); font-size: 0.9rem; margin-bottom: 5px; }
.metric-value { font-size: 1.8rem; font-weight: 700; color: var(--text-color); }
.metric-value.positive { color: var(--success-color); }
.metric-value.negative { color: var(--danger-color); }
.footer { 
  margin-top: 50px; padding-top: 20px; 
  border-top: 1px solid var(--border-color); 
  color: var(--muted-color); font-size: 0.85rem; text-align: center;
}
.badge { 
  display: inline-block; padding: 4px 10px; border-radius: 4px; 
  font-size: 0.8rem; font-weight: 600;
}
.badge-success { background: #c6f6d5; color: #276749; }
.badge-danger { background: #fed7d7; color: #c53030; }
.badge-warning { background: #fefcbf; color: #975a16; }
.page-break { page-break-before: always; margin-top: 40px; }
@media print { 
  body { margin: 15px; padding: 15px; }
  .metric-grid { grid-template-columns: repeat(2, 1fr); }
  .no-print { display: none; }
}
@media (max-width: 768px) {
  body { padding: 20px; }
  .metric-grid { grid-template-columns: 1fr; }
}
</style>
</head>
<body>
<div class="container">
)";
    }
    
    void add_header(const ExtendedReportConfig& config) {
        oss_ << "<div class='header'>\n";
        oss_ << "<h1>" << config.title << "</h1>\n";
        oss_ << "<div class='meta'>";
        if (!config.account_name.empty()) {
            oss_ << "<strong>" << config.account_name << "</strong>";
            if (!config.account_id.empty()) {
                oss_ << " &bull; Account: " << config.account_id;
            }
            oss_ << "<br>";
        }
        if (!config.period_start.empty() && !config.period_end.empty()) {
            oss_ << "Period: " << config.period_start << " to " << config.period_end << "<br>";
        }
        oss_ << "Generated: " << config.generated_at;
        oss_ << "</div>\n";
        oss_ << "</div>\n";
    }
    
    void start_section(const std::string& title) {
        oss_ << "<div class='section'>\n<h2>" << title << "</h2>\n";
    }
    
    void end_section() { oss_ << "</div>\n"; }
    
    void add_subsection(const std::string& title) {
        oss_ << "<h3>" << title << "</h3>\n";
    }
    
    void add_paragraph(const std::string& text) {
        oss_ << "<p>" << text << "</p>\n";
    }
    
    void start_table(const std::vector<std::string>& headers) {
        oss_ << "<table>\n<thead><tr>\n";
        for (const auto& h : headers) {
            oss_ << "<th>" << h << "</th>\n";
        }
        oss_ << "</tr></thead>\n<tbody>\n";
    }
    
    void add_table_row(const std::vector<std::string>& cells,
                       const std::vector<bool>& is_numeric = {}) {
        oss_ << "<tr>\n";
        for (size_t i = 0; i < cells.size(); ++i) {
            bool numeric = i < is_numeric.size() && is_numeric[i];
            std::string cell_class = numeric ? "number" : "";
            
            if (numeric && !cells[i].empty()) {
                double val = 0;
                try {
                    std::string clean = cells[i];
                    clean.erase(std::remove(clean.begin(), clean.end(), '$'), clean.end());
                    clean.erase(std::remove(clean.begin(), clean.end(), '%'), clean.end());
                    clean.erase(std::remove(clean.begin(), clean.end(), ','), clean.end());
                    val = std::stod(clean);
                    if (val > 0) cell_class += " positive";
                    else if (val < 0) cell_class += " negative";
                } catch (...) {}
            }
            
            oss_ << "<td class='" << cell_class << "'>" << cells[i] << "</td>\n";
        }
        oss_ << "</tr>\n";
    }
    
    void end_table() { oss_ << "</tbody></table>\n"; }
    
    void add_summary_box(const std::string& content) {
        oss_ << "<div class='summary-box'>" << content << "</div>\n";
    }
    
    void start_metric_grid() { oss_ << "<div class='metric-grid'>\n"; }
    void end_metric_grid() { oss_ << "</div>\n"; }
    
    void add_metric(const std::string& label, const std::string& value,
                    const std::string& extra_class = "") {
        oss_ << "<div class='metric-card'>\n"
             << "<div class='metric-label'>" << label << "</div>\n"
             << "<div class='metric-value " << extra_class << "'>" << value << "</div>\n"
             << "</div>\n";
    }
    
    void add_page_break() { oss_ << "<div class='page-break'></div>\n"; }
    
    void add_footer(const std::string& text) {
        oss_ << "<div class='footer'>" << text << "</div>\n";
    }
    
    void end_document() {
        oss_ << "</div>\n</body>\n</html>";
    }
    
    std::string build() const { return oss_.str(); }
    void clear() { oss_.str(""); oss_.clear(); }

private:
    std::ostringstream oss_;
};

// ============================================================================
// Account Statement Generator
// ============================================================================

/**
 * @brief Account statement data structure
 */
struct AccountStatementData {
    trading::UnifiedAccount account;
    std::vector<trading::UnifiedPosition> positions;
    std::vector<trading::UnifiedOrder> orders;
    std::vector<tax::RealizedGainLoss> realized_gains;
    
    double beginning_value{0};
    double ending_value{0};
    double deposits{0};
    double withdrawals{0};
    double dividends{0};
    double interest{0};
    double fees{0};
    double realized_gain_loss{0};
    double unrealized_gain_loss{0};
};

/**
 * @brief Generate account statement HTML
 */
inline std::string generate_account_statement_html(
    const AccountStatementData& data,
    const ExtendedReportConfig& config) {
    
    EnhancedHTMLBuilder html;
    
    ExtendedReportConfig cfg = config;
    if (cfg.title.empty()) cfg.title = "Account Statement";
    if (cfg.account_name.empty()) cfg.account_name = data.account.name;
    if (cfg.account_id.empty()) cfg.account_id = data.account.broker_account_id;
    
    html.start_document(cfg.title);
    html.add_header(cfg);
    
    // Account Summary
    html.start_section("Account Summary");
    html.start_metric_grid();
    html.add_metric("Portfolio Value", fmt_currency(data.account.portfolio_value));
    html.add_metric("Cash Balance", fmt_currency(data.account.cash));
    html.add_metric("Buying Power", fmt_currency(data.account.buying_power));
    html.add_metric("Margin Used", fmt_currency(data.account.margin_used));
    html.end_metric_grid();
    html.end_section();
    
    // Period Activity
    html.start_section("Period Activity");
    html.start_table({"Description", "Amount"});
    html.add_table_row({"Beginning Value", fmt_currency(data.beginning_value)}, {false, true});
    html.add_table_row({"Deposits", fmt_currency(data.deposits)}, {false, true});
    html.add_table_row({"Withdrawals", fmt_currency(-data.withdrawals)}, {false, true});
    html.add_table_row({"Dividends", fmt_currency(data.dividends)}, {false, true});
    html.add_table_row({"Interest", fmt_currency(data.interest)}, {false, true});
    html.add_table_row({"Fees", fmt_currency(-data.fees)}, {false, true});
    html.add_table_row({"Realized Gain/Loss", fmt_currency(data.realized_gain_loss)}, {false, true});
    html.add_table_row({"Unrealized Gain/Loss", fmt_currency(data.unrealized_gain_loss)}, {false, true});
    html.add_table_row({"<strong>Ending Value</strong>", 
                       "<strong>" + fmt_currency(data.ending_value) + "</strong>"}, {false, true});
    html.end_table();
    html.end_section();
    
    // Holdings
    if (!data.positions.empty()) {
        html.start_section("Current Holdings");
        html.start_table({"Symbol", "Qty", "Avg Cost", "Price", "Value", "Gain/Loss", "%"});
        
        double total_value = 0, total_gain = 0;
        for (const auto& pos : data.positions) {
            total_value += pos.market_value;
            total_gain += pos.unrealized_pl;
            
            html.add_table_row({
                pos.symbol,
                fmt_number(pos.qty, pos.qty == std::floor(pos.qty) ? 0 : 4),
                fmt_currency(pos.avg_entry_price),
                fmt_currency(pos.current_price),
                fmt_currency(pos.market_value),
                fmt_currency(pos.unrealized_pl),
                fmt_percent(pos.unrealized_pl_pct)
            }, {false, true, true, true, true, true, true});
        }
        
        html.add_table_row({
            "<strong>Total</strong>", "", "", "",
            "<strong>" + fmt_currency(total_value) + "</strong>",
            "<strong>" + fmt_currency(total_gain) + "</strong>", ""
        }, {false, false, false, false, true, true, false});
        
        html.end_table();
        html.end_section();
    }
    
    // Orders
    if (!data.orders.empty()) {
        html.start_section("Recent Orders");
        html.start_table({"Date", "Symbol", "Side", "Type", "Qty", "Price", "Status"});
        
        int count = 0;
        for (const auto& order : data.orders) {
            if (++count > 50) break;
            
            html.add_table_row({
                order.created_at.substr(0, 10),
                order.symbol,
                trading::order_side_to_string(order.side),
                trading::order_type_to_string(order.type),
                fmt_number(order.qty, 0),
                order.filled_avg_price > 0 ? fmt_currency(order.filled_avg_price) :
                    (order.limit_price > 0 ? fmt_currency(order.limit_price) : "MKT"),
                trading::order_status_to_string(order.status)
            }, {false, false, false, false, true, true, false});
        }
        
        html.end_table();
        html.end_section();
    }
    
    html.add_footer(cfg.footer_text);
    html.end_document();
    
    return html.build();
}

// ============================================================================
// Performance Report Generator
// ============================================================================

/**
 * @brief Performance report data structure
 */
struct PerformanceReportData {
    double total_return_pct{0};
    double annualized_return{0};
    double ytd_return{0};
    double mtd_return{0};
    
    double sharpe_ratio{0};
    double sortino_ratio{0};
    double calmar_ratio{0};
    double information_ratio{0};
    
    double volatility{0};
    double max_drawdown{0};
    double beta{0};
    double alpha{0};
    double tracking_error{0};
    
    double win_rate{0};
    int total_trades{0};
    int winning_trades{0};
    int losing_trades{0};
    double avg_win{0};
    double avg_loss{0};
    double profit_factor{0};
    
    std::string benchmark_name{"S&P 500"};
    double benchmark_return{0};
    
    std::map<std::string, double> monthly_returns;
    std::map<std::string, double> sector_allocation;
};

/**
 * @brief Generate performance report HTML
 */
inline std::string generate_performance_report_html(
    const PerformanceReportData& data,
    const ExtendedReportConfig& config) {
    
    EnhancedHTMLBuilder html;
    
    ExtendedReportConfig cfg = config;
    if (cfg.title.empty()) cfg.title = "Performance Report";
    
    html.start_document(cfg.title);
    html.add_header(cfg);
    
    // Key Metrics
    html.start_section("Performance Summary");
    html.start_metric_grid();
    html.add_metric("Total Return", fmt_percent(data.total_return_pct),
                   data.total_return_pct >= 0 ? "positive" : "negative");
    html.add_metric("Annualized", fmt_percent(data.annualized_return));
    html.add_metric("YTD Return", fmt_percent(data.ytd_return));
    html.add_metric("MTD Return", fmt_percent(data.mtd_return));
    html.end_metric_grid();
    html.end_section();
    
    // Risk-Adjusted
    html.start_section("Risk-Adjusted Returns");
    html.start_table({"Metric", "Value", "Description"});
    html.add_table_row({"Sharpe Ratio", fmt_number(data.sharpe_ratio),
                       "Risk-adjusted return (higher is better)"}, {false, true, false});
    html.add_table_row({"Sortino Ratio", fmt_number(data.sortino_ratio),
                       "Downside risk-adjusted return"}, {false, true, false});
    html.add_table_row({"Calmar Ratio", fmt_number(data.calmar_ratio),
                       "Return / Max Drawdown"}, {false, true, false});
    html.add_table_row({"Information Ratio", fmt_number(data.information_ratio),
                       "Active return per tracking error"}, {false, true, false});
    html.end_table();
    html.end_section();
    
    // Risk Metrics
    html.start_section("Risk Analysis");
    html.start_metric_grid();
    html.add_metric("Volatility", fmt_percent(data.volatility));
    html.add_metric("Max Drawdown", fmt_percent(data.max_drawdown), "negative");
    html.add_metric("Beta", fmt_number(data.beta));
    html.add_metric("Alpha", fmt_percent(data.alpha));
    html.end_metric_grid();
    html.end_section();
    
    // Benchmark Comparison
    html.start_section("Benchmark Comparison");
    double excess = data.total_return_pct - data.benchmark_return;
    html.start_table({"Metric", "Portfolio", data.benchmark_name, "Excess"});
    html.add_table_row({"Total Return", fmt_percent(data.total_return_pct),
                       fmt_percent(data.benchmark_return), fmt_percent(excess)},
                      {false, true, true, true});
    html.add_table_row({"Tracking Error", fmt_percent(data.tracking_error), "-", "-"},
                      {false, true, false, false});
    html.end_table();
    html.end_section();
    
    // Trading Stats
    html.start_section("Trading Statistics");
    html.start_table({"Metric", "Value"});
    html.add_table_row({"Total Trades", std::to_string(data.total_trades)}, {false, true});
    html.add_table_row({"Winning Trades", std::to_string(data.winning_trades)}, {false, true});
    html.add_table_row({"Losing Trades", std::to_string(data.losing_trades)}, {false, true});
    html.add_table_row({"Win Rate", fmt_percent(data.win_rate)}, {false, true});
    html.add_table_row({"Average Win", fmt_currency(data.avg_win)}, {false, true});
    html.add_table_row({"Average Loss", fmt_currency(data.avg_loss)}, {false, true});
    html.add_table_row({"Profit Factor", fmt_number(data.profit_factor)}, {false, true});
    html.end_table();
    html.end_section();
    
    // Monthly Returns
    if (!data.monthly_returns.empty()) {
        html.add_page_break();
        html.start_section("Monthly Returns");
        
        std::map<int, std::map<int, double>> yearly;
        for (const auto& [month, ret] : data.monthly_returns) {
            int year = std::stoi(month.substr(0, 4));
            int mon = std::stoi(month.substr(5, 2));
            yearly[year][mon] = ret;
        }
        
        html.start_table({"Year", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                         "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "YTD"});
        
        for (const auto& [year, months] : yearly) {
            std::vector<std::string> row = {std::to_string(year)};
            double total = 0;
            
            for (int m = 1; m <= 12; ++m) {
                auto it = months.find(m);
                if (it != months.end()) {
                    row.push_back(fmt_percent(it->second));
                    total += it->second;
                } else {
                    row.push_back("-");
                }
            }
            row.push_back(fmt_percent(total));
            
            std::vector<bool> numeric(14, true);
            numeric[0] = false;
            html.add_table_row(row, numeric);
        }
        
        html.end_table();
        html.end_section();
    }
    
    html.add_footer(cfg.footer_text);
    html.end_document();
    
    return html.build();
}

// ============================================================================
// Trade Confirmation Generator
// ============================================================================

/**
 * @brief Trade confirmation data
 */
struct TradeConfirmationData {
    std::string confirmation_number;
    std::string trade_date;
    std::string settlement_date;
    std::string account_id;
    std::string account_name;
    
    std::string symbol;
    std::string security_name;
    std::string side;
    double quantity{0};
    double price{0};
    double principal{0};
    double commission{0};
    double fees{0};
    double net_amount{0};
    
    std::string order_type;
    std::string time_in_force;
    std::string execution_venue;
};

/**
 * @brief Generate trade confirmation HTML
 */
inline std::string generate_trade_confirmation_html(
    const TradeConfirmationData& trade,
    const ExtendedReportConfig& config) {
    
    EnhancedHTMLBuilder html;
    
    ExtendedReportConfig cfg = config;
    cfg.title = "Trade Confirmation";
    cfg.account_name = trade.account_name;
    cfg.account_id = trade.account_id;
    
    html.start_document(cfg.title);
    html.add_header(cfg);
    
    html.start_section("Transaction Details");
    html.start_table({"", ""});
    html.add_table_row({"Confirmation Number", trade.confirmation_number});
    html.add_table_row({"Trade Date", trade.trade_date});
    html.add_table_row({"Settlement Date", trade.settlement_date});
    html.add_table_row({"Transaction Type", trade.side});
    html.end_table();
    html.end_section();
    
    html.start_section("Security Information");
    html.start_table({"", ""});
    html.add_table_row({"Symbol", trade.symbol});
    html.add_table_row({"Description", trade.security_name});
    html.add_table_row({"Quantity", fmt_number(trade.quantity,
                       trade.quantity == std::floor(trade.quantity) ? 0 : 4)});
    html.add_table_row({"Price", fmt_currency(trade.price)});
    html.end_table();
    html.end_section();
    
    html.start_section("Transaction Summary");
    html.start_table({"Description", "Amount"});
    html.add_table_row({"Principal", fmt_currency(trade.principal)}, {false, true});
    if (trade.commission > 0) {
        html.add_table_row({"Commission", fmt_currency(trade.commission)}, {false, true});
    }
    if (trade.fees > 0) {
        html.add_table_row({"Fees", fmt_currency(trade.fees)}, {false, true});
    }
    html.add_table_row({"<strong>Net Amount</strong>",
                       "<strong>" + fmt_currency(trade.net_amount) + "</strong>"},
                      {false, true});
    html.end_table();
    html.end_section();
    
    html.add_footer(cfg.footer_text);
    html.end_document();
    
    return html.build();
}

// ============================================================================
// Tax Report Generator (Form 8949)
// ============================================================================

/**
 * @brief Generate Form 8949 tax report HTML
 */
inline std::string generate_tax_report_html(
    const std::vector<tax::Form8949Line>& lines,
    int tax_year,
    const ExtendedReportConfig& config) {
    
    EnhancedHTMLBuilder html;
    
    ExtendedReportConfig cfg = config;
    cfg.title = "Capital Gains and Losses - Tax Year " + std::to_string(tax_year);
    
    html.start_document(cfg.title);
    html.add_header(cfg);
    
    // Group by box
    std::map<char, std::vector<const tax::Form8949Line*>> by_box;
    for (const auto& line : lines) {
        by_box[line.form_box].push_back(&line);
    }
    
    std::map<char, std::string> box_titles = {
        {'A', "Part I - Short-Term (Box A): Basis reported to IRS"},
        {'B', "Part I - Short-Term (Box B): Basis reported, adjustments needed"},
        {'C', "Part I - Short-Term (Box C): Basis NOT reported to IRS"},
        {'D', "Part II - Long-Term (Box D): Basis reported to IRS"},
        {'E', "Part II - Long-Term (Box E): Basis reported, adjustments needed"},
        {'F', "Part II - Long-Term (Box F): Basis NOT reported to IRS"}
    };
    
    for (char box : {'A', 'B', 'C', 'D', 'E', 'F'}) {
        auto it = by_box.find(box);
        if (it == by_box.end() || it->second.empty()) continue;
        
        if (box == 'D') html.add_page_break();
        
        html.start_section(box_titles[box]);
        html.start_table({"Description", "Acquired", "Sold", "Proceeds",
                         "Cost Basis", "Code", "Adj", "Gain/Loss"});
        
        double total_proceeds = 0, total_cost = 0, total_adj = 0, total_gain = 0;
        
        for (const auto* line : it->second) {
            total_proceeds += line->proceeds;
            total_cost += line->cost_basis;
            total_adj += line->adjustment_amount;
            total_gain += line->gain_loss;
            
            html.add_table_row({
                line->description,
                line->date_acquired,
                line->date_sold,
                fmt_currency(line->proceeds),
                fmt_currency(line->cost_basis),
                line->adjustment_code,
                line->adjustment_amount != 0 ? fmt_currency(line->adjustment_amount) : "",
                fmt_currency(line->gain_loss)
            }, {false, false, false, true, true, false, true, true});
        }
        
        html.add_table_row({
            "<strong>Totals</strong>", "", "",
            "<strong>" + fmt_currency(total_proceeds) + "</strong>",
            "<strong>" + fmt_currency(total_cost) + "</strong>", "",
            total_adj != 0 ? "<strong>" + fmt_currency(total_adj) + "</strong>" : "",
            "<strong>" + fmt_currency(total_gain) + "</strong>"
        }, {false, false, false, true, true, false, true, true});
        
        html.end_table();
        html.end_section();
    }
    
    // Summary
    html.start_section("Summary");
    
    double st_total = 0, lt_total = 0;
    for (const auto& line : lines) {
        if (line.is_short_term) st_total += line.gain_loss;
        else lt_total += line.gain_loss;
    }
    
    html.start_table({"Category", "Total"});
    html.add_table_row({"Short-Term Capital Gains/Losses", fmt_currency(st_total)}, {false, true});
    html.add_table_row({"Long-Term Capital Gains/Losses", fmt_currency(lt_total)}, {false, true});
    html.add_table_row({"<strong>Net Capital Gain/Loss</strong>",
                       "<strong>" + fmt_currency(st_total + lt_total) + "</strong>"}, {false, true});
    html.end_table();
    
    html.add_summary_box(
        "<strong>Important:</strong> This report is for informational purposes only. "
        "Please consult a tax professional before filing. "
        "Verify all data against your broker's 1099-B."
    );
    
    html.end_section();
    html.add_footer(cfg.footer_text);
    html.end_document();
    
    return html.build();
}

/**
 * @brief Generate Form 8949 CSV export
 */
inline std::string generate_tax_report_csv(const std::vector<tax::Form8949Line>& lines) {
    std::ostringstream oss;
    
    oss << "Description,Date Acquired,Date Sold,Proceeds,Cost Basis,"
        << "Adjustment Code,Adjustment Amount,Gain/Loss,Term,Box\n";
    
    for (const auto& line : lines) {
        oss << "\"" << line.description << "\","
            << line.date_acquired << ","
            << line.date_sold << ","
            << std::fixed << std::setprecision(2)
            << line.proceeds << ","
            << line.cost_basis << ","
            << line.adjustment_code << ","
            << line.adjustment_amount << ","
            << line.gain_loss << ","
            << (line.is_short_term ? "Short" : "Long") << ","
            << line.form_box << "\n";
    }
    
    return oss.str();
}

// ============================================================================
// Risk Report Generator
// ============================================================================

/**
 * @brief Risk report data structure
 */
struct RiskReportData {
    double var_95_1d{0};
    double var_99_1d{0};
    double var_95_10d{0};
    double cvar_95{0};
    
    struct PositionRisk {
        std::string symbol;
        double market_value{0};
        double weight{0};
        double volatility{0};
        double beta{0};
        double var_contribution{0};
        double marginal_var{0};
    };
    std::vector<PositionRisk> position_risks;
    
    double top_5_concentration{0};
    double herfindahl_index{0};
    
    struct StressScenario {
        std::string name;
        double impact{0};
        std::string description;
    };
    std::vector<StressScenario> stress_tests;
    
    struct RiskLimit {
        std::string metric;
        double current{0};
        double limit{0};
        bool breached{false};
    };
    std::vector<RiskLimit> risk_limits;
};

/**
 * @brief Generate risk report HTML
 */
inline std::string generate_risk_report_html(
    const RiskReportData& data,
    const ExtendedReportConfig& config) {
    
    EnhancedHTMLBuilder html;
    
    ExtendedReportConfig cfg = config;
    cfg.title = "Portfolio Risk Report";
    
    html.start_document(cfg.title);
    html.add_header(cfg);
    
    // VaR Summary
    html.start_section("Value at Risk (VaR)");
    html.start_metric_grid();
    html.add_metric("1-Day VaR (95%)", fmt_currency(data.var_95_1d), "negative");
    html.add_metric("1-Day VaR (99%)", fmt_currency(data.var_99_1d), "negative");
    html.add_metric("10-Day VaR (95%)", fmt_currency(data.var_95_10d), "negative");
    html.add_metric("CVaR / ES (95%)", fmt_currency(data.cvar_95), "negative");
    html.end_metric_grid();
    
    html.add_paragraph(
        "Value at Risk represents the maximum expected loss at the given confidence level. "
        "CVaR (Conditional VaR) shows the expected loss when losses exceed VaR."
    );
    html.end_section();
    
    // Position Risk
    if (!data.position_risks.empty()) {
        html.start_section("Position Risk Analysis");
        html.start_table({"Symbol", "Value", "Weight", "Vol", "Beta", "VaR Contrib", "Marginal"});
        
        for (const auto& pr : data.position_risks) {
            html.add_table_row({
                pr.symbol,
                fmt_currency(pr.market_value),
                fmt_percent(pr.weight),
                fmt_percent(pr.volatility),
                fmt_number(pr.beta),
                fmt_currency(pr.var_contribution),
                fmt_currency(pr.marginal_var)
            }, {false, true, true, true, true, true, true});
        }
        
        html.end_table();
        html.end_section();
    }
    
    // Concentration
    html.start_section("Concentration Risk");
    html.start_table({"Metric", "Value", "Assessment"});
    
    std::string conc_assess = data.top_5_concentration > 50 ?
        "<span class='warning'>High - Consider diversifying</span>" : "Acceptable";
    html.add_table_row({"Top 5 Concentration", fmt_percent(data.top_5_concentration),
                       conc_assess}, {false, true, false});
    
    std::string hhi_assess = data.herfindahl_index > 0.25 ?
        "<span class='warning'>Concentrated</span>" :
        (data.herfindahl_index > 0.15 ? "Moderate" : "Diversified");
    html.add_table_row({"HHI Index", fmt_number(data.herfindahl_index), hhi_assess},
                      {false, true, false});
    
    html.end_table();
    html.end_section();
    
    // Stress Tests
    if (!data.stress_tests.empty()) {
        html.start_section("Stress Test Scenarios");
        html.start_table({"Scenario", "Impact", "Description"});
        
        for (const auto& st : data.stress_tests) {
            html.add_table_row({st.name, fmt_currency(st.impact), st.description},
                              {false, true, false});
        }
        
        html.end_table();
        html.end_section();
    }
    
    // Risk Limits
    if (!data.risk_limits.empty()) {
        html.start_section("Risk Limit Monitoring");
        html.start_table({"Metric", "Current", "Limit", "Status"});
        
        for (const auto& rl : data.risk_limits) {
            std::string status = rl.breached ?
                "<span class='badge badge-danger'>BREACHED</span>" :
                "<span class='badge badge-success'>OK</span>";
            
            html.add_table_row({rl.metric, fmt_number(rl.current), fmt_number(rl.limit), status},
                              {false, true, true, false});
        }
        
        html.end_table();
        html.end_section();
    }
    
    html.add_footer(cfg.footer_text);
    html.end_document();
    
    return html.build();
}

// ============================================================================
// File Output Utilities
// ============================================================================

/**
 * @brief Write report content to file
 */
inline bool write_report_file(const std::string& content, const std::string& filepath) {
    try {
        std::ofstream file(filepath);
        if (!file.is_open()) return false;
        file << content;
        return file.good();
    } catch (...) {
        return false;
    }
}

} // namespace genie::reporting

#endif // GENIE_REPORTING_EXTENDED_HPP
